### ISSUE TITLE
Build Your Own URL Shortener with Firebase Dynamic Links

### ISSUE THREAD

**Issue by RakeshPotnuru** [gdsclpu/articles#1]
### Topic name
Build Your Own URL Shortener with Firebase Dynamic Links

### Type (Article/Snippet)

Article

### Would you like to work on this? (Yes/No)

Yes

### Tasks

- [x] SEO-optimized title
- [x] SEO-optimized description
- [x] Featured Image
- [x] Followed Writers' and editors' guidelines
- [x] Minimum and maximum length check (Min: 500 words for an article and 100 words for a snippet; Max: no-limit for an article and 300 words for a snippet)

### Links

Main blog - https://blog.gdsclpu.live/build-your-own-url-shortener-with-firebase-dynamic-links
Medium - https://medium.com/dsc-lpu/build-your-own-url-shortener-with-firebase-dynamic-links-3301a4c8d1f5
Dev - https://dev.to/gdsclpu/build-your-own-url-shortener-with-firebase-dynamic-links-59oi
Hashnode - https://gdsclpu.hashnode.dev/build-your-own-url-shortener-with-firebase-dynamic-links
