### ISSUE TITLE
Learn TensorFlow

### ISSUE THREAD

**Issue by iprajwaal** [gdsclpu/articles#12]
### Type (Article/Snippet)
Article ✅

### Would you like to work on this? (Yes/No)
Yes  ✅
### Tasks 

- [x] SEO-optimized title
- [x] SEO-optimized description
- [x] Featured Image
- [x] Followed Writers' and editors' guidelines
- [x] Minimum and maximum length check (Min: 500 words for an article and 100 words for a snippet; Max: no-limit for an article and 300 words for a snippet)

### Links

- [x] Main blog - https://blog.gdsclpu.live/tensorflow-mastery-unlock-the-ml-power-and-potential
- [x] Medium - https://medium.com/@prajwaal/tfug-fe4704fce21a
- [x] Dev - https://dev.to/gdsclpu/tensorflow-mastery-unlock-the-ml-power-potential-b0i
- [x] Hashnode - https://prajwaal.live/tensorflow-mastery-unlock-the-ml-power-potential

**Comment by RakeshPotnuru** [comment]
@prajwal3104 After publishing on all platforms, add links by editing the issue.
