### ISSUE TITLE
Learn TensorFlow - 2

### ISSUE THREAD

**Issue by iprajwaal** [gdsclpu/articles#13]
Learn TensorFlow - 2
Type (Article/Snippet)
Article ✅

Would you like to work on this? (Yes/No)
Yes ✅

### Tasks 

- [x] SEO-optimized title
- [x] SEO-optimized description
- [x] Featured Image
- [x] Followed Writers' and editors' guidelines
- [x] Minimum and maximum length check (Min: 500 words for an article and 100 words for a snippet; Max: no-limit for an article and 300 words for a snippet)

### Links

- [x] Main blog - https://blog.gdsclpu.live/optimizing-tensorflow-code-for-performance-and-exportability
- [x] Medium -  https://prajwaal.medium.com/optimizing-tensorflow-code-for-performance-and-exportability-3deb59da312f
- [x] Dev - https://dev.to/prajwaal/optimizing-tensorflow-code-for-performance-and-exportability-43ol
- [x] Hashnode - https://prajwaal.live/optimizing-tensorflow-code-for-performance-and-exportability
