### ISSUE TITLE
Introduction to Tensors

### ISSUE THREAD

**Issue by iprajwaal** [gdsclpu/articles#14]
### Type (Article/Snippet)
Article

### Would you like to work on this? (Yes/No)
Yes

### Tasks 

- [x] SEO-optimized title
- [x] SEO-optimized description
- [x] Featured Image
- [x] Followed Writers' and editors' guidelines
- [x] Minimum and maximum length check (Min: 500 words for an article and 100 words for a snippet; Max: no-limit for an article and 300 words for a snippet)

### Links

- [x] Main blog - https://blog.gdsclpu.live/tensor-basics-types-operations-and-applications
- [ ] Medium - 
- [ ] Dev - 
- [ ] Hashnode -
