### ISSUE TITLE
Create Your First React App

### ISSUE THREAD

**Issue by RamanSharma100** [gdsclpu/articles#3]
### Topic name
Create Your First React App

### Type (Article/Snippet)
Article

### Would you like to work on this? (Yes/No)
Yes

### Tasks 

- [ ] SEO-optimized title
- [ ] SEO-optimized description
- [ ] Featured Image
- [ ] Followed Writers' and editors' guidelines
- [ ] Minimum and maximum length check (Min: 500 words for an article and 100 words for a snippet; Max: no-limit for an article and 300 words for a snippet)

### Links

- [ ] Main blog - 
- [ ] Medium - 
- [ ] Dev - 
- [ ] Hashnode -
