### ISSUE TITLE
Cloud with GCP ☁️

### ISSUE THREAD

**Issue by iprajwaal** [gdsclpu/articles#4]
### Topic name
Cloud with GCP ☁️

### Type (Article/Snippet)
Article

### Would you like to work on this? (Yes/No)
Yes

### Tasks 

- [x] SEO-optimized title
- [x] SEO-optimized description
- [x] Featured Image
- [x] Followed Writers' and editors' guidelines
- [x] Minimum and maximum length check (Min: 500 words for an article and 100 words for a snippet; Max: no-limit for an article and 300 words for a snippet)

### Links

- [x] Main blog - https://blog.gdsclpu.live/master-cloud-computing-with-gcp-powerful-solutions
- [x] Medium - https://medium.com/gdsclpu/master-cloud-computing-with-gcp-powerful-solutions-ada424157739
- [x] Dev - https://dev.to/gdsclpu/master-cloud-computing-with-gcp-powerful-solutions-3g51
- [x] Hashnode - https://prajwaal.live/master-cloud-computing-with-gcp-powerful-solutions

**Comment by RakeshPotnuru** [comment]
@prajwal3104 
can you provide a little description of what you will cover in this?

**Comment by iprajwaal** [comment]
@RakeshPotnuru 

Sure!! 1st I would like to **explain** _**what is cloud**_, then with this context I would like to move on with **Google cloud service** and what are the service and products they offer. Why it is most chosen cloud service now a days.

And this not the end of it I would like to explain and elaborate each and every service available in up-coming **Articles**

**Comment by RakeshPotnuru** [comment]
@prajwal3104 Add links in issue.
