### ISSUE TITLE
Google Apps Script

### ISSUE THREAD

**Issue by surajmani-dev** [gdsclpu/articles#5]
### Type (Article/Snippet)
Article
### Would you like to work on this? (Yes/No)
Yes
### Tasks 

- [x] SEO-optimized title
- [x] SEO-optimized description
- [x] Featured Image
- [x] Followed Writers' and editors' guidelines
- [ ] Minimum and maximum length check (Min: 500 words for an article and 100 words for a snippet; Max: no-limit for an article and 300 words for a snippet)

### Links

- [ ] Main blog - 
- [ ] Medium - 
- [ ] Dev - 
- [ ] Hashnode -
