### ISSUE TITLE
Getting started with Firebase for web development

### ISSUE THREAD

**Issue by RakeshPotnuru** [gdsclpu/articles#6]
### Topic name
Getting started with Firebase for web development

### Type (Article/Snippet)
Article

### Would you like to work on this? (Yes/No)
Yes

### Tasks 

- [x] SEO-optimized title
- [x] SEO-optimized description
- [x] Featured Image
- [x] Followed Writers' and editors' guidelines
- [x] Minimum and maximum length check (Min: 500 words for an article and 100 words for a snippet; Max: no-limit for an article and 300 words for a snippet)

### Links

Main blog - https://blog.gdsclpu.live/getting-started-with-firebase-for-web-development
Medium - https://medium.com/gdsclpu/getting-started-with-firebase-for-web-development-ffffdbdd540e
Dev - https://dev.to/gdsclpu/getting-started-with-firebase-for-web-development-35a1
Hashnode - https://gdsclpu.hashnode.dev/getting-started-with-firebase-for-web-development
